package phase3;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.*;
import javax.swing.border.MatteBorder;

import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;

/**
 *
 * @author firasfares
 */
public class ForgetPassword extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    /**
     * Creates new form ForgetPassword
     */
    private JFrame f = new JFrame("ForgetPassword");
    public ForgetPassword()  {
        initComponents();
        
        setVisible(true);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    ForgetPassword(String userSes) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {
        reset = new javax.swing.JButton();
        reset.setRolloverIcon(new ImageIcon(ForgetPassword.class.getResource("Images/resetHover1.png")));
        reset.setIcon(new ImageIcon(ForgetPassword.class.getResource("Images/reset.png")));
        reset.setBorder(null);
        reset.setContentAreaFilled(false);
        reset.setBorderPainted(false);

        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    resetActionPerformed();
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                }
            }});



        newpass = new javax.swing.JTextField();
        newpass.setBorder(new MatteBorder(5, 5, 5, 5, (Color) new Color(0, 0, 0)));
        newpass.setBackground(new Color(226, 225, 225));
		newpass.setFont(new Font("Dialog",Font.BOLD,20));
		
        confpass = new javax.swing.JTextField();
        confpass.setBorder(new MatteBorder(5, 5, 5, 5, (Color) new Color(0, 0, 0)));
        confpass.setBackground(new Color(226, 225, 225));
		confpass.setFont(new Font("Dialog",Font.BOLD,20));
		
        email = new javax.swing.JTextField();
        email.setBorder(new MatteBorder(5, 5, 5, 5, (Color) new Color(0, 0, 0)));
        email.setBackground(new Color(226, 225, 225));
		email.setFont(new Font("Dialog",Font.BOLD,20));
		
        Background = new javax.swing.JLabel();
        Background.setIcon(new ImageIcon(ForgetPassword.class.getResource("Images/pic4.png")));
        Background.setDisabledIcon(new ImageIcon(login.class.getResource("Images/pic4.png")));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        
        JLabel title = new JLabel();
        title.setIcon(new ImageIcon(ForgetPassword.class.getResource("Images/testlogo4.png")));
        title.setBounds(191, 0, 658, 160);
        getContentPane().add(title);
        getContentPane().add(reset);
        reset.setBounds(384, 585, 205, 89);
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        getContentPane().add(newpass);
        newpass.setBounds(500, 448, 279, 61);
        confpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confpassActionPerformed(evt);
            }
        });
        getContentPane().add(confpass);
        confpass.setBounds(500, 330, 279, 61);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(500, 212, 279, 61);

        Background.setBackground(new java.awt.Color(255, 51, 51));
        Background.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setEnabled(false);
        Background.setFocusable(false);
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Background.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BackgroundComponentAdded(evt);
            }
        });
        Background.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BackgroundFocusLost(evt);
            }
        });
        
        label = new JLabel();
        label.setIcon(new ImageIcon(ForgetPassword.class.getResource("Images/email5.png")));
        label.setFont(new Font("Dialog", Font.BOLD, 25));
        label.setBounds(205, 195, 285, 96);
        getContentPane().add(label);
        
        label_1 = new JLabel();
        label_1.setIcon(new ImageIcon(ForgetPassword.class.getResource("Images/newPass12.png")));
        label_1.setFont(new Font("Dialog", Font.BOLD, 25));
        label_1.setBounds(205, 311, 285, 105);
        getContentPane().add(label_1);
        
        label_2 = new JLabel();
        label_2.setIcon(new ImageIcon(ForgetPassword.class.getResource("Images/confPass2.png")));
        label_2.setFont(new Font("Dialog", Font.BOLD, 25));
        label_2.setBounds(205, 427, 306, 117);
        getContentPane().add(label_2);
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1008, 729);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed() throws SQLException {
        String pass1 = String.valueOf(newpass.getText());
        String email1 =  String.valueOf(email.getText());
        String confpass1 = String.valueOf(confpass.getText());
        email1 = Base64.getEncoder().encodeToString(email1.getBytes());
        if (pass1.equals("")) {
            JOptionPane.showMessageDialog(null, "Add a password");
        } else if (email1.equals("")) {
            JOptionPane.showMessageDialog(null, "Add a email");
        } else if (confpass1.equals("")) {
            JOptionPane.showMessageDialog(null, "Add a conf password");
        } else if (!confpass1.equals(pass1)) {
            JOptionPane.showMessageDialog(null, "confirm password and password didn't match");
        }

        //checking if matching email
        PreparedStatement ps;
        ps = Myconnection.getconnection().prepareStatement("SELECT * FROM numbercruncher.student where student_email=?");
        ps.setString(1, email1);
        //Check user name if exist
        ResultSet r1 = ps.executeQuery();
        try {
            //if email matching update password
            if (r1.next()) {
                pass1 = Base64.getEncoder().encodeToString(pass1.getBytes());
                confpass1=Base64.getEncoder().encodeToString(confpass1.getBytes());

                String query = "Update numbercruncher.student set student_pass = ? , student_confpass = ? where student_email = ?";

                //set values
                ps = Myconnection.getconnection().prepareStatement(query);
                ps.setString(1, pass1);
                ps.setString(2, confpass1);
                ps.setString(3, email1);

                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Password Updated");
                    try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;
                            }
                        }
                    } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    login login = new login();
                    setVisible(false);

                    login.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "error");
                }

            } else {//printing email error
                JOptionPane.showMessageDialog(null, "your email don't match an account on our system check your email please if you don't have account please sign up  thank you");
            }

        }catch(SQLException throwables){
            throwables.printStackTrace();
        }
    }







    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_newpassActionPerformed

    private void confpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confpassActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        
    }//GEN-LAST:event_resetMouseClicked

    private void BackgroundComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BackgroundComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BackgroundComponentAdded

    private void BackgroundFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BackgroundFocusLost

    }//GEN-LAST:event_BackgroundFocusLost

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField confpass;
    private javax.swing.JTextField email;
    private javax.swing.JTextField newpass;
    private JButton reset;
    private JLabel label;
    private JLabel label_1;
    private JLabel label_2;
}
