package phase3;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author firasfares
 */
public class login extends JFrame {
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form login
	 */

	public login() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		Login = new JButton();//login btn
		Login.setRolloverIcon(new ImageIcon(login.class.getResource("Images/loginHoverTry2.png")));//login img hover
		Login.setOpaque(false);
		Login.setIcon(new ImageIcon(login.class.getResource("Images/loginTry2.png")));//login img
		Login.setFocusable(false);
		Login.setContentAreaFilled(false);
		Login.setBorderPainted(false);
		Login.setSize(185, 97);
		jPasswordField = new javax.swing.JPasswordField();//pass field
		Guest = new javax.swing.JToggleButton();//guest btn
		Guest.setRolloverIcon(new ImageIcon(login.class.getResource("Images/guestModeHover.png")));//guest img
		Guest.setIcon(new ImageIcon(login.class.getResource("Images/guestMode.png")));//guest img hvr
		Guest.setFocusable(false);
		Guest.setBorderPainted(false);
		Guest.setContentAreaFilled(false);
		PassWord = new JLabel();//pass lable
		PassWord.setIcon(new ImageIcon(login.class.getResource("Images/password.png")));//pass img
		UserName = new JLabel();//username lable
		UserName.setIcon(new ImageIcon(login.class.getResource("Images/username.png")));//username img;
		ForgetPass = new JButton();//forgpass bttn
		ForgetPass.setRolloverIcon(new ImageIcon(login.class.getResource("Images/ForgotPasswordHover.png")));//forpass imghvr
		ForgetPass.setContentAreaFilled(false);
		ForgetPass.setIcon(new ImageIcon(login.class.getResource("Images/ForgotPassword5.png")));//forpass img
		ForgetPass.setFocusable(false);
		ForgetPass.setBorderPainted(false);
		signup = new JButton();//sign up btn
		signup.setRolloverIcon(new ImageIcon(login.class.getResource("Images/signupHover.png")));//signup imghvr
		signup.setIcon(new ImageIcon(login.class.getResource("Images/signup.png")));//sign up img
		signup.setFocusable(false);
		signup.setOpaque(false);
		signup.setContentAreaFilled(false);
		signup.setBorderPainted(false);
		unameField = new javax.swing.JTextField();//uname field
		unameField.setBackground(new Color(226, 225, 225));//uname bg
		unameField.setFont(new Font("Dialog",Font.BOLD,20));
		
		jPasswordField.setBackground(new Color(226, 225, 225));//pass field bg
		jPasswordField.setFont(new Font("Dialog", Font.BOLD, 20));
		Showpass = new javax.swing.JCheckBox();//check box pass
		Showpass.setForeground(Color.BLACK);//showpass color
		Showpass.setContentAreaFilled(false);
		
		try{
	           Font font = Font.createFont(Font.TRUETYPE_FONT, login.class.getResourceAsStream("Bungee-Regular.ttf"));
	           Showpass.setFont(font.deriveFont(Font.BOLD, 15f));
		}
		catch(Exception e){}
		
		

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);//exit on close
		setTitle("Number Crunchers\n");//title

		setMinimumSize(new java.awt.Dimension(1024, 768));
		setPreferredSize(new java.awt.Dimension(1024, 768));
		setResizable(false);
		setSize(new java.awt.Dimension(1024, 768));
		getContentPane().setLayout(null);
		Login.setBorder(null);
		Guest.setBorder(null);

		signup.setBorder(null);
		ForgetPass.setBorder(null);
		unameField.setBorder(new MatteBorder(5, 5, 5, 5, (Color) new Color(0, 0, 0)));
		jPasswordField.setBorder(new MatteBorder(5, 5, 5, 5, (Color) new Color(0, 0, 0)));

		Login.addMouseListener(new java.awt.event.MouseAdapter() {//login btn mouse clicked
			public void mousePressed(MouseEvent evt) {
				LoginMouseClicked(evt);
			}
		});
		Login.addActionListener(new ActionListener() {//login btn mouse action performed
			public void actionPerformed(ActionEvent evt) {
				LoginActionPerformed(evt);
			}
		});
		
		JLabel lblNewLabel_1 = new JLabel("");//avatar
		lblNewLabel_1.setIcon(new ImageIcon(login.class.getResource("Images/avatar4.png")));
		lblNewLabel_1.setBounds(117, 223, 100, 100);
		getContentPane().add(lblNewLabel_1);
		getContentPane().add(Login);
		Login.setBounds(458, 475, 185, 96);


		getContentPane().add(jPasswordField);
		jPasswordField.setBounds(447, 350, 279, 61);

		
		Guest.addMouseListener(new java.awt.event.MouseAdapter() {//guest btn mouse  clicked
			public void mousePressed(MouseEvent evt) {
				GuestMouseClicked(evt);
			}
		});
		Guest.addActionListener(new ActionListener() {//guest btn mouse action performed
			public void actionPerformed(ActionEvent evt) {
				GuestActionPerformed(evt);
			}
		});
		getContentPane().add(Guest);
		Guest.setBounds(0, 0, 203, 119);

		PassWord.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
		PassWord.setText("Password");//pass lable
		getContentPane().add(PassWord);
		PassWord.setBounds(214, 334, 223, 96);

		UserName.setFont(new java.awt.Font("Lucida Grande", Font.BOLD, 25)); // NOI18N
		getContentPane().add(UserName);//username lable
		UserName.setBounds(214, 227, 223, 96);

		ForgetPass.addMouseListener(new java.awt.event.MouseAdapter() {//forgtpass btn clicked
			public void mousePressed(MouseEvent evt) {
				ForgetPassMouseClicked(evt);
			}
		});
		ForgetPass.addActionListener(new ActionListener() {//forgtpass btn mouse action performed
			public void actionPerformed(ActionEvent evt) {
				ForgetPassActionPerformed(evt);
			}
		});
		getContentPane().add(ForgetPass);
		ForgetPass.setBounds(75, 451, 373, 150);

		
		signup.addMouseListener(new java.awt.event.MouseAdapter() {//signup btn mouse clicked
			public void mousePressed(MouseEvent evt) {
				signupMouseClicked(evt);
			}
		});
		signup.addActionListener(new ActionListener() {//signup btn mouse action performed
			public void actionPerformed(ActionEvent evt) {
				signupActionPerformed(evt);
			}
		});
		getContentPane().add(signup);
		signup.setBounds(653, 475, 221, 96);
		getContentPane().add(unameField);
		unameField.setBounds(447, 245, 279, 61);

		Showpass.setText("Show Password");//lable show pass
		Showpass.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(MouseEvent evt) {
				ShowpassMouseClicked(evt);
			}
		});
		getContentPane().add(Showpass);
		Showpass.setBounds(468, 425, 210, 23);
		
		lblNewLabel = new JLabel();
		lblNewLabel.setIcon(new ImageIcon(login.class.getResource("Images/testlogo4.png")));//test logo image
		lblNewLabel.setBounds(191, 63, 658, 160);
		getContentPane().add(lblNewLabel);
		background = new JLabel();
		background.setIcon(new ImageIcon(login.class.getResource("Images/background2.jpg")));//bg image
		background.setDisabledIcon(new ImageIcon(login.class.getResource("Images/pic4.png")));
		background.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
		background.setEnabled(false);
		background.setFocusable(false);
		background.setPreferredSize(new java.awt.Dimension(1920, 1080));
		background.addContainerListener(new java.awt.event.ContainerAdapter() {
			public void componentAdded(java.awt.event.ContainerEvent evt) {
				backgroundComponentAdded(evt);
			}
		});
		background.addFocusListener(new java.awt.event.FocusAdapter() {//bg focus
			public void focusLost(java.awt.event.FocusEvent evt) {
				backgroundFocusLost(evt);
			}
		});

		label = new JLabel("");
		label.setIcon(new ImageIcon(login.class.getResource("Images/lock8.png")));//lock iamge
		label.setBounds(95, 334, 108, 96);
		getContentPane().add(label);
		getContentPane().add(background);
		background.setBounds(0, 0, 1018, 739);

		setBounds(0, 0, 380, 326);
	}// </editor-fold>//GEN-END:initComponents

	private static class RoundedBorder implements Border {

		private int radius;

		RoundedBorder(int radius) {
			this.radius = radius;
		}

		public Insets getBorderInsets(Component c) {
			return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
		}

		public boolean isBorderOpaque() {
			return true;
		}

		public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
			g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
		}
	}

	private void jPasswordFieldActionPerformed(ActionEvent evt) {// GEN-FIRST:event_jPasswordFieldActionPerformed

	}// GEN-LAST:event_jPasswordFieldActionPerformed

	private void ForgetPassMouseClicked(MouseEvent evt) {// GEN-FIRST:event_ForgetPassMouseClicked

	}// GEN-LAST:event_ForgetPassMouseClicked

	private void signupMouseClicked(MouseEvent evt) {// GEN-FIRST:event_signupMouseClicked

	}// GEN-LAST:event_signupMouseClicked

	private void GuestActionPerformed(ActionEvent evt) {// GEN-FIRST:event_GuestActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_GuestActionPerformed

	private void LoginActionPerformed(ActionEvent evt) {// GEN-FIRST:event_LoginActionPerformed



		PreparedStatement ps; ResultSet rs;
		Myconnection conn = new Myconnection();//connect
		String uname = unameField.getText();//set username from field
		String pass = String.valueOf(jPasswordField.getText());//set pass from field
		pass = Base64.getEncoder().encodeToString(pass.getBytes());
		 getdata[0]=uname;//store uname in getdata
		String query="SELECT * FROM numbercruncher.student where student_user = ? and student_pass = ?";//check username and pass in database

		try {

			ps = conn.getconnection().prepareStatement(query);//call the query

			ps.setString(1, uname); ps.setString(2, pass);//insert index data

			rs = ps.executeQuery();//execute

			if(rs.next()) { JOptionPane.showMessageDialog(this, "Login Successful");//check if it's maching
				try {
					for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
						if ("Nimbus".equals(info.getName())) {
							javax.swing.UIManager.setLookAndFeel(info.getClassName());
							break;
						}
					}
				} catch (ClassNotFoundException ex) {
					java.util.logging.Logger.getLogger(homepagev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				} catch (InstantiationException ex) {
					java.util.logging.Logger.getLogger(homepagev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				} catch (IllegalAccessException ex) {
					java.util.logging.Logger.getLogger(homepagev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				} catch (javax.swing.UnsupportedLookAndFeelException ex) {
					java.util.logging.Logger.getLogger(homepagev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				}
				homepagev2 homepagev2 = new homepagev2();//caling home page
				homepagev2.setVisible(true);
				setVisible(false);}else{//closing login
				JOptionPane.showMessageDialog(this, "Invalid Username or Password"); }

		} catch (SQLException ex) {
			Logger.getLogger(phase3.login.class.getName()).log(Level.SEVERE, null, ex); }

		// Coding Part of LOGIN button



	}// GEN-LAST:event_LoginActionPerformed

	public void addActionEvent() {
		Login.addActionListener((ActionListener) this);
		ForgetPass.addActionListener((ActionListener) this);
		Showpass.addActionListener((ActionListener) this);
	}

	public void actionPerformed(ActionEvent e) {
	}

	private void LoginMouseClicked(MouseEvent evt) {// GEN-FIRST:event_LoginMouseClicked


	}// GEN-LAST:event_LoginMouseClicked

	private void backgroundFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_backgroundFocusLost

	}// GEN-LAST:event_backgroundFocusLost

	private void backgroundComponentAdded(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_backgroundComponentAdded
		// TODO add your handling code here:
	}// GEN-LAST:event_backgroundComponentAdded

	private void ForgetPassActionPerformed(ActionEvent evt) {// GEN-FIRST:event_ForgetPassActionPerformed
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		ForgetPassword ForgetPassword = new ForgetPassword();//calling forgtpass
		ForgetPassword.setVisible(true);
		setVisible(false);//close login

	}// GEN-LAST:event_ForgetPassActionPerformed

	private void signupActionPerformed(ActionEvent evt) {// GEN-FIRST:event_signupActionPerformed
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
		}
		SignUp SignUp = new SignUp();//calling signup
		SignUp.setVisible(true);
		setVisible(false);//closing login
	}// GEN-LAST:event_signupActionPerformed

	private void ShowpassMouseClicked(MouseEvent evt) {// GEN-FIRST:event_ShowpassMouseClicked
		if (Showpass.isSelected()) {//showing pass
			jPasswordField.setEchoChar((char) 0);
		} else {
			jPasswordField.setEchoChar('*');
		}
	}// GEN-LAST:event_ShowpassMouseClicked

	private void GuestMouseClicked(MouseEvent evt) {// GEN-FIRST:event_GuestMouseClicked

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(guestpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(guestpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(guestpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(guestpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		 guestpage guestpage = new guestpage();//calling guest page
		guestpage.setVisible(true);
		setVisible(false);//closing login
	}// GEN-LAST:event_GuestMouseClicked

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 * 
		 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
		 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
		 * ("Nimbus".equals(info.getName())) {
		 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
		 * (ClassNotFoundException ex) {
		 * java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch (InstantiationException ex) {
		 * java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch (IllegalAccessException ex) {
		 * java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch
		 * (javax.swing.UnsupportedLookAndFeelException ex) {
		 * java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } //</editor-fold>
		 * 
		 * /* Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new RunnableImpl());

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public static String [] getdata = new String[1];
	private JButton ForgetPass;
	private javax.swing.JToggleButton Guest;
	private JButton Login;
	private JLabel PassWord;
	private javax.swing.JCheckBox Showpass;
	private JLabel UserName;
	private JLabel background;
	private javax.swing.JPasswordField jPasswordField;
	private JButton signup;
	private javax.swing.JTextField unameField;
	private JLabel lblNewLabel;
	private JLabel label;
	// End of variables declaration//GEN-END:variables

	private static class RunnableImpl implements Runnable {

		public RunnableImpl() {
		}

		public void run() {
			new login().setVisible(true);
		}
	}
}
