/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author firasfares
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup = new javax.swing.JButton();
        NC = new javax.swing.JTextField();
        newpass = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        confpass = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        confpassField = new javax.swing.JPasswordField();
        fnameField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        unameField = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("signup");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(0, 23));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1280, 853));
        getContentPane().setLayout(null);

        signup.setText("SignUp");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(130, 260, 140, 29);

        NC.setEditable(false);
        NC.setBackground(new java.awt.Color(204, 0, 0));
        NC.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        NC.setForeground(new java.awt.Color(153, 0, 0));
        NC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NC.setText("Number Crunchers");
        NC.setToolTipText("Number Crunchers");
        NC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        NC.setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));
        NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NCActionPerformed(evt);
            }
        });
        getContentPane().add(NC);
        NC.setBounds(6, 6, 380, 51);

        newpass.setText("Password");
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        getContentPane().add(newpass);
        newpass.setBounds(10, 160, 134, 26);

        LastName.setText("Last Name");
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        getContentPane().add(LastName);
        LastName.setBounds(10, 100, 134, 26);

        email.setText("Email");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(10, 230, 134, 26);
        getContentPane().add(PassField);
        PassField.setBounds(193, 163, 200, 26);

        username.setText("UserName");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(10, 130, 134, 26);

        confpass.setText("Conf Password");
        confpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confpassActionPerformed(evt);
            }
        });
        getContentPane().add(confpass);
        confpass.setBounds(10, 200, 134, 26);

        firstname.setText("First Name");
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname);
        firstname.setBounds(10, 70, 134, 26);
        getContentPane().add(confpassField);
        confpassField.setBounds(190, 200, 200, 26);
        getContentPane().add(fnameField);
        fnameField.setBounds(190, 70, 200, 26);
        getContentPane().add(lnameField);
        lnameField.setBounds(190, 100, 200, 26);
        getContentPane().add(emailField);
        emailField.setBounds(190, 230, 200, 26);
        getContentPane().add(unameField);
        unameField.setBounds(190, 130, 200, 26);

        Background.setBackground(new java.awt.Color(255, 51, 51));
        Background.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setEnabled(false);
        Background.setFocusable(false);
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Background.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BackgroundComponentAdded(evt);
            }
        });
        Background.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BackgroundFocusLost(evt);
            }
        });
        getContentPane().add(Background);
        Background.setBounds(0, 0, 390, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NCActionPerformed

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        
            String fname = fnameField.getText();
            String lname = lnameField.getText();
            String uname = unameField.getText();
            String pass = String.valueOf(PassField.getText());
            String email = emailField.getText();
            String confpass = String.valueOf(confpassField.getText());
            
                if(fname.equals("")){
                    JOptionPane.showMessageDialog(null,"Add a first name");
                }else if(lname.equals("")){
                    JOptionPane.showMessageDialog(null,"Add a last name");
                }else if(uname.equals("")){
                    JOptionPane.showMessageDialog(null,"Add a user name");
                }else if(pass.equals("")){
                    JOptionPane.showMessageDialog(null,"Add a password");
                }else if(email.equals("")){
                    JOptionPane.showMessageDialog(null,"Add a email");
                }else if(confpass.equals("")){
                    JOptionPane.showMessageDialog(null,"Add a conf password");
                }else if(!confpass.equals(pass)){
                    JOptionPane.showMessageDialog(null,"conf password and password didn't match");
                }
            
            PreparedStatement ps;
            String query = "inset into student ('name','password','confpass','fname','lname','email') values (?,?,?,?,?,?)";
        try {  
            
            ps = Myconnection.getconnection().prepareStatement(query);
            
            ps.setString(1, uname);
            ps.setString(2, pass);
            ps.setString(3, confpass);
            ps.setString(4, fname);
            ps.setString(5, lname);
            ps.setString(6, email);
            
            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null,"New User Add");
            }else{
                JOptionPane.showMessageDialog(null,"error");
            }
                
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_signupActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void confpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confpassActionPerformed

    private void BackgroundComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BackgroundComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BackgroundComponentAdded

    private void BackgroundFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BackgroundFocusLost

    }//GEN-LAST:event_BackgroundFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField NC;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JTextField confpass;
    private javax.swing.JPasswordField confpassField;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField fnameField;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField newpass;
    private javax.swing.JButton signup;
    private javax.swing.JTextField unameField;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
